#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width        0
bspc config window_gap          30
bspc config top_padding 	40

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xrandr --output eDP-1 --mode 2880x1800 --rate 120.00

xinput set-prop "12" "Coordinate Transformation Matrix" 2 0 0 0 2 0 0 0 1
xinput set-prop "12" "libinput Accel Speed" 0.25

export CM_LAUNCHER=rofi

xsetroot -cursor_name left_ptr
xrdb -merge ~/.Xresources

pactl set-sink-mute @DEFAULT_SINK@ toggle && pactl set-sink-mute @DEFAULT_SINK@ toggle

systemctl --user import-environment DISPLAY

clipmenud &
libinput-gestures-setup start &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
feh --bg-scale /usr/share/backgrounds/wallpaper.png &
dunst &
killall nm-applet && nm-applet &
$HOME/.config/polybar/launch.sh &
