#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

export XCURSOR_SIZE=32
xinput set-prop "12" "Coordinate Transformation Matrix" 2 0 0 0 2 0 0 0 1 # This is for the touchpad
xsetroot -cursor_name left_ptr
xrdb -merge ~/.Xresources

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
